// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbWZ8Wny2ETECfyZsex09xKnjH9cxDzSQ',
    appId: '1:922677263772:web:4cf8fbb993e5f3f7db1c59',
    messagingSenderId: '922677263772',
    projectId: 'socially-6ad1c',
    authDomain: 'socially-6ad1c.firebaseapp.com',
    storageBucket: 'socially-6ad1c.firebasestorage.app',
    measurementId: 'G-7NEMRBKF72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfhAx7-rpgIFDZUPnS9oL3Tx_6j32RTbw',
    appId: '1:922677263772:android:2a8a40db226f4d31db1c59',
    messagingSenderId: '922677263772',
    projectId: 'socially-6ad1c',
    storageBucket: 'socially-6ad1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1MVZSO1UjcCdtf_QpksSHeiRon6oVAXk',
    appId: '1:922677263772:ios:a3ac3e8505745126db1c59',
    messagingSenderId: '922677263772',
    projectId: 'socially-6ad1c',
    storageBucket: 'socially-6ad1c.firebasestorage.app',
    iosBundleId: 'com.example.sociallyApp',
  );
}
